from __future__ import annotations

from typing import List, Dict

POLICY_OPTIONS: List[Dict[str, object]] = [
    {
        "id": "rapid_employer_outreach",
        "title": "Rapid employer outreach and placement support",
        "description": "Coordinate with local employers to identify immediate openings and match job seekers quickly.",
        "pros": "Fast-to-deploy support for displaced workers.",
        "cons": "Relies on near-term labor demand being available.",
        "implementation_notes": "Leverage workforce boards and existing employer networks.",
        "cost": "low",
        "speed": "high",
        "equity": "medium",
        "market": "high",
        "feasibility": "high",
        "risk": "low",
        "sectors": ["labor_market"],
        "effects": {
            "labor_unemployment_bls": 0.35,
            "labor_unemployment_fred": 0.3,
        },
    },
    {
        "id": "skills_apprenticeship",
        "title": "Sector-based upskilling and apprenticeships",
        "description": "Expand short-cycle credentials and apprenticeships aligned to regional demand.",
        "pros": "Improves long-term earnings and mobility.",
        "cons": "Training pipelines take time to scale.",
        "implementation_notes": "Pair training with employer commitments and wraparound supports.",
        "cost": "medium",
        "speed": "medium",
        "equity": "high",
        "market": "medium",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["labor_market", "education"],
        "effects": {
            "labor_unemployment_bls": 0.25,
            "labor_unemployment_fred": 0.2,
            "education_grad_rate": 0.15,
            "business_startup_rate": 0.1,
        },
    },
    {
        "id": "childcare_transport_support",
        "title": "Childcare and transportation access",
        "description": "Expand access to childcare and transportation assistance for working households.",
        "pros": "Boosts labor force participation and stability.",
        "cons": "Requires coordination across agencies and providers.",
        "implementation_notes": "Target high-need corridors and integrate with workforce placements.",
        "cost": "high",
        "speed": "medium",
        "equity": "high",
        "market": "medium",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["labor_market", "housing"],
        "effects": {
            "labor_unemployment_bls": 0.2,
            "labor_unemployment_fred": 0.2,
            "housing_rent_burden": 0.15,
        },
    },
    {
        "id": "affordable_housing_acceleration",
        "title": "Affordable housing pipeline acceleration",
        "description": "Streamline approvals and expand financing for affordable housing construction.",
        "pros": "Addresses supply constraints and rent pressures.",
        "cons": "Requires capital and multi-year delivery timelines.",
        "implementation_notes": "Prioritize shovel-ready projects and public-private partnerships.",
        "cost": "high",
        "speed": "low",
        "equity": "high",
        "market": "medium",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["housing"],
        "effects": {
            "housing_median_rent": 0.35,
            "housing_rent_burden": 0.3,
            "housing_vacancy_rate": 0.25,
            "housing_home_value": -0.1,
        },
    },
    {
        "id": "zoning_modernization",
        "title": "Zoning and permitting modernization",
        "description": "Modernize zoning and permitting to enable more housing types and faster approvals.",
        "pros": "Unlocks private supply and lowers soft costs.",
        "cons": "Requires local buy-in and careful community engagement.",
        "implementation_notes": "Pair with design standards and transit-oriented priorities.",
        "cost": "low",
        "speed": "medium",
        "equity": "medium",
        "market": "high",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["housing", "infrastructure"],
        "effects": {
            "housing_median_rent": 0.25,
            "housing_vacancy_rate": 0.2,
            "housing_home_value": -0.05,
        },
    },
    {
        "id": "rental_assistance_preservation",
        "title": "Rental assistance and preservation",
        "description": "Expand rental assistance and preserve naturally affordable housing stock.",
        "pros": "Provides immediate relief to cost-burdened renters.",
        "cons": "Requires ongoing funding to sustain impact.",
        "implementation_notes": "Target high-need neighborhoods and prevent displacement.",
        "cost": "high",
        "speed": "high",
        "equity": "high",
        "market": "low",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["housing"],
        "effects": {
            "housing_rent_burden": 0.35,
            "housing_median_rent": 0.15,
        },
    },
    {
        "id": "fiscal_reserve_strategy",
        "title": "Fiscal reserve and stabilization strategy",
        "description": "Strengthen rainy-day reserves and volatility buffers.",
        "pros": "Improves resilience to revenue shocks.",
        "cons": "May constrain near-term spending flexibility.",
        "implementation_notes": "Align reserve targets with volatility exposure.",
        "cost": "medium",
        "speed": "medium",
        "equity": "medium",
        "market": "medium",
        "feasibility": "high",
        "risk": "low",
        "sectors": ["fiscal"],
        "effects": {
            "fiscal_real_gdp": 0.05,
        },
    },
    {
        "id": "performance_budgeting",
        "title": "Performance budgeting and program reallocation",
        "description": "Reallocate spending toward high-impact programs and sunset low-impact ones.",
        "pros": "Improves return on public spending.",
        "cons": "Requires strong data and stakeholder alignment.",
        "implementation_notes": "Use outcome targets and multi-year reviews.",
        "cost": "low",
        "speed": "medium",
        "equity": "medium",
        "market": "medium",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["fiscal", "general"],
        "effects": {
            "fiscal_real_gdp": 0.1,
        },
    },
    {
        "id": "early_learning_support",
        "title": "Early learning and tutoring acceleration",
        "description": "Scale evidence-based tutoring and early literacy interventions.",
        "pros": "Improves long-term educational outcomes.",
        "cons": "Requires sustained staffing and funding.",
        "implementation_notes": "Coordinate across districts and target high-need schools.",
        "cost": "medium",
        "speed": "medium",
        "equity": "high",
        "market": "low",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["education"],
        "effects": {
            "education_grad_rate": 0.25,
            "labor_unemployment_bls": 0.1,
        },
    },
    {
        "id": "behavioral_health_access",
        "title": "Behavioral health access expansion",
        "description": "Increase capacity for behavioral health and substance use services.",
        "pros": "Addresses acute health and workforce barriers.",
        "cons": "Requires workforce expansion and sustained funding.",
        "implementation_notes": "Invest in provider pipeline and telehealth.",
        "cost": "high",
        "speed": "medium",
        "equity": "high",
        "market": "low",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["health", "labor_market"],
        "effects": {
            "health_chronic_rate": 0.2,
            "labor_unemployment_fred": 0.1,
        },
    },
    {
        "id": "chronic_prevention",
        "title": "Chronic disease prevention investment",
        "description": "Scale preventive care and community health initiatives.",
        "pros": "Reduces long-term healthcare costs.",
        "cons": "Benefits accrue over longer timeframes.",
        "implementation_notes": "Partner with local health systems and community orgs.",
        "cost": "medium",
        "speed": "low",
        "equity": "high",
        "market": "low",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["health"],
        "effects": {
            "health_chronic_rate": 0.3,
        },
    },
    {
        "id": "flood_resilience",
        "title": "Flood resilience and mitigation program",
        "description": "Invest in flood mitigation, coastal protection, and resilient design standards.",
        "pros": "Reduces climate risk and recovery costs.",
        "cons": "Capital intensive and multi-year delivery.",
        "implementation_notes": "Prioritize high-risk zones and critical infrastructure.",
        "cost": "high",
        "speed": "low",
        "equity": "medium",
        "market": "medium",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["climate", "infrastructure"],
        "effects": {
            "climate_risk_index": 0.3,
            "infrastructure_road_condition": 0.1,
        },
    },
    {
        "id": "transport_asset_management",
        "title": "Transportation asset management",
        "description": "Accelerate maintenance to reduce backlog and improve roadway conditions.",
        "pros": "Improves reliability and safety.",
        "cons": "Requires sustained funding.",
        "implementation_notes": "Use asset management plans and performance targets.",
        "cost": "high",
        "speed": "medium",
        "equity": "medium",
        "market": "medium",
        "feasibility": "high",
        "risk": "low",
        "sectors": ["infrastructure"],
        "effects": {
            "infrastructure_road_condition": 0.3,
        },
    },
    {
        "id": "air_quality_enforcement",
        "title": "Targeted air quality enforcement",
        "description": "Strengthen monitoring and mitigation in high-exposure corridors.",
        "pros": "Improves health and compliance outcomes.",
        "cons": "Requires coordination with industry and local agencies.",
        "implementation_notes": "Align enforcement with public health data.",
        "cost": "medium",
        "speed": "medium",
        "equity": "high",
        "market": "low",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["environment", "health"],
        "effects": {
            "environment_pm25": 0.25,
            "health_chronic_rate": 0.1,
        },
    },
    {
        "id": "public_safety_violence_prevention",
        "title": "Violence prevention and community safety",
        "description": "Blend targeted enforcement with community-based prevention programs.",
        "pros": "Reduces violent crime and improves neighborhood stability.",
        "cons": "Requires cross-agency coordination.",
        "implementation_notes": "Use data-led deployment and community partnerships.",
        "cost": "medium",
        "speed": "medium",
        "equity": "medium",
        "market": "low",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["public_safety"],
        "effects": {
            "public_safety_violent_crime": 0.35,
        },
    },
    {
        "id": "grid_modernization",
        "title": "Grid modernization and energy efficiency",
        "description": "Invest in grid modernization and energy efficiency upgrades.",
        "pros": "Improves reliability and lowers long-term energy costs.",
        "cons": "Requires utility coordination and capital investment.",
        "implementation_notes": "Prioritize high-need feeders and efficiency incentives.",
        "cost": "high",
        "speed": "low",
        "equity": "medium",
        "market": "medium",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["energy", "climate"],
        "effects": {
            "energy_retail_price": 0.15,
            "climate_risk_index": 0.1,
        },
    },
    {
        "id": "broadband_last_mile",
        "title": "Last-mile broadband expansion",
        "description": "Expand high-speed broadband access in underserved areas.",
        "pros": "Boosts economic access and digital equity.",
        "cons": "Build-out can take time in rural areas.",
        "implementation_notes": "Combine public grants with private matching.",
        "cost": "high",
        "speed": "medium",
        "equity": "high",
        "market": "medium",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["broadband", "education", "business_dynamism"],
        "effects": {
            "broadband_access": 0.35,
            "education_grad_rate": 0.1,
            "business_startup_rate": 0.1,
        },
    },
    {
        "id": "migration_attraction",
        "title": "Talent attraction and retention",
        "description": "Incentivize in-migration of skilled workers and retain graduates.",
        "pros": "Strengthens labor supply and innovation base.",
        "cons": "Requires sustained incentives and quality-of-life investments.",
        "implementation_notes": "Pair with housing affordability and job growth efforts.",
        "cost": "medium",
        "speed": "medium",
        "equity": "medium",
        "market": "high",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["demographics", "labor_market"],
        "effects": {
            "demographics_net_migration": 0.3,
            "labor_unemployment_bls": 0.1,
        },
    },
    {
        "id": "small_business_capital",
        "title": "Small business capital access",
        "description": "Expand loan guarantees and technical assistance for small businesses.",
        "pros": "Supports entrepreneurship and job creation.",
        "cons": "Requires underwriting discipline and oversight.",
        "implementation_notes": "Partner with community lenders and incubators.",
        "cost": "medium",
        "speed": "medium",
        "equity": "high",
        "market": "high",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["business_dynamism", "labor_market"],
        "effects": {
            "business_startup_rate": 0.35,
            "labor_unemployment_fred": 0.1,
        },
    },
    {
        "id": "agriculture_resilience",
        "title": "Climate-smart agriculture and water efficiency",
        "description": "Invest in irrigation upgrades and climate-smart farming practices.",
        "pros": "Improves yields and resilience to climate volatility.",
        "cons": "Requires technical support and capital.",
        "implementation_notes": "Leverage USDA programs and extension services.",
        "cost": "medium",
        "speed": "low",
        "equity": "medium",
        "market": "medium",
        "feasibility": "medium",
        "risk": "medium",
        "sectors": ["agriculture", "climate"],
        "effects": {
            "agriculture_yield": 0.3,
            "climate_risk_index": 0.1,
        },
    },
]


def get_policy_options(issue_area: str) -> List[Dict[str, object]]:
    if issue_area == "all":
        return POLICY_OPTIONS.copy()
    filtered = [
        policy for policy in POLICY_OPTIONS
        if issue_area in policy.get("sectors", []) or "general" in policy.get("sectors", [])
    ]
    return filtered or POLICY_OPTIONS.copy()
